services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: anilyfe-app
    container_name: anilyfe

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
